# Generated by Django 3.0.7 on 2020-06-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_weiboprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='updated_time',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='updated_time',
            new_name='update_time',
        ),
    ]
